name: Build package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # step 2: generate build files and dump inside the workspace directory of the runner
    - name: Generate build files
      uses: thatisuday/go-build-action@v1
      with:
        platforms: "linux/amd64"
        package: "zdns"
        name: "zdns"
        compress: "true"
        dest: "dist"
      
    - uses: actions/upload-artifact@v3
      with:
        name: release
        path: ./dist/*.tar.gz
